version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
    steps:
      - checkout # checkout the repository from github
      - run: npm install
      # run tests!
      - run: npm test